### ISSUE TITLE
Thanks - info inside

### ISSUE THREAD

**Issue by piejanssens** [romanvm/service.addic7ed#1]
Just quick message to say thanks. Great to see someone taking the initiative to make a new and working Kodi add-on for Addic7ed.

FYI, I spoke with someone from Addic7ed couple of months back via FB and they have nothing (anymore) against having an 'official' add-on which would be available in the official Kodi repo.

**Comment by romanvm** [comment]
Just for clarification: this is a completely independent project that exists for some time with no relation to other similar projects that may exist or have existed, so there's no "pick up" and "again".

As for Addic7ed guys changing their opinion, could you provide a link for that? As a Team Kodi member, I may be interested in including this addon into the official repo.

**Comment by piejanssens** [comment]
https://www.facebook.com/Addic7ed/posts/10152734938466723

**Comment by romanvm** [comment]
Thanks. I asked them if their opinion hasn't changed since then (2015).

**Comment by piejanssens** [comment]
FYI - I've just reached out via the forum's contact form. Hopefully they will come back.

**Comment by romanvm** [comment]
Thank you. Please keep me posted.

**Comment by romanvm** [comment]
See: xbmc/repo-scripts#919
