### ISSUE TITLE
daily download limit

### ISSUE THREAD

**Issue by sergio49650** [romanvm/service.addic7ed#10]
Hi,
In the parser.py, you put a daily download limit to 10. But on the addic7ed site (I have an account) the limit is 40. would it be possible to change this ?

Thanks

**Comment by romanvm** [comment]
There is nothing to change: such limit does not exist anywhere in the code.

**Comment by sergio49650** [comment]
Even at the end of parser.py ?-------- Message original --------Objet : Re: [romanvm/service.addic7ed] daily download limit (#10)De : Roman Miroshnychenko À : "romanvm/service.addic7ed" Cc : sergio49650 ,Author There is nothing to change: such limit does not exist anywhere in the code.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/romanvm/service.addic7ed","title":"romanvm/service.addic7ed","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/romanvm/service.addic7ed"}},"updates":{"snippets":[{"icon":"PERSON","message":"@romanvm in #10: There is nothing to change: such limit does not exist anywhere in the code."}],"action":{"name":"View Issue","url":"https://github.com/romanvm/service.addic7ed/issues/10#issuecomment-478519436"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/romanvm/service.addic7ed/issues/10#issuecomment-478519436",
"url": "https://github.com/romanvm/service.addic7ed/issues/10#issuecomment-478519436",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by romanvm** [comment]
> Even at the end of parser.py 

Even there. If you can't read the code, please don't jump into conclusions.
