### ISSUE TITLE
ERROR: GetDirectory - Error getting plugin://service.subtitles.rvm.addic7ed/?action=search&languages=French&preferredlanguage=French

### ISSUE THREAD

**Issue by FabricePMD** [romanvm/service.addic7ed#11]
Hi Roman, 

few days ago, i have an issue with the plugin. Can't download any subtitle from addic7ed. 

Here is the kodi log if you see something wrong.

Thanks and have a nice day ! 

[01_KODI.log](https://github.com/romanvm/service.addic7ed/files/3174924/01_KODI.log)

**Comment by romanvm** [comment]
Looks like you have some old version of BeautifulSoup4 module installed. Go to addon manager - subtitles - select this Addic7ed.com addon - click "Dependencies" - select BeautifulSoup4 and then update it to the latest available version.

**Comment by FabricePMD** [comment]
You've got right ! Thanks for the time and the solution! Issue closed ;-)
