### ISSUE TITLE
Do you have a kodi repo ?  installing from zip is tricky with your current git structure 

### ISSUE THREAD

**Issue by SerpentDrago** [romanvm/service.addic7ed#13]
You have the addon in a subfolder of the this git repo , this makes it a bit of a pain to install the addon . as i need to download the git zip , then extract it , then zip up just the addon folder . 

Thanks :)

**Comment by romanvm** [comment]
I don't know what to say to this. Have you tried to read the Readme for this repo?

**Comment by SerpentDrago** [comment]
"This addon is available in Subtitles section of the official Kodi addon repository and can be installed via Kodi Addon "

My bad , was it always available ? Sorry never even thought to check that !!  Sorry for your time .
