### ISSUE TITLE
Error when downloading a subtitle

### ISSUE THREAD

**Issue by lynx31** [romanvm/service.addic7ed#15]
**Issue description:**
I am getting an error, when trying to download a subtitle file via the add-on

**Kodi debug log:**
Here's a link to the debug log: 
http://paste.kodi.tv/ikuvivopel

**Additional context**
The same thing started happening on 1 other device.
Update - it appears that this is actually happening for only 1 tv show - Unforgotten (as you will see in the log file), but for all of its episodes. Might have to do something with the way the file is named

**Comment by romanvm** [comment]
> Might have to do something with the way the file is named

Yes, looks like it. Why does it have Cyrillic "х" in the filename?

**Comment by lynx31** [comment]
> > Might have to do something with the way the file is named
> 
> Yes, looks like it. Why does it have Cyrillic "х" in the filename?

Don't know, maybe a mistake by whoever named it. Anyway, if that's the cause, then the issue is solved for me. Up to you to decide if its a bug or not

**Comment by romanvm** [comment]
I think it can be fixed.
