### ISSUE TITLE
Unable to determine episode data for <episode_name>

### ISSUE THREAD

**Issue by Dreamwork57** [romanvm/service.addic7ed#20]
Hi ! I recently installed your add-on on kodi because it's the more updated for french subtitles.
But I'm sometimes experiencing an issue and the logs aren't that much helping : 

`service.subtitles.rvm.addic7ed: Searching for subs...
service.subtitles.rvm.addi7ed: Unable to determine episode data for <EPISODE_NAME>`

And... That's pretty all...
I tried to change the source of the episode, reinstall the addi7ed plugin, reboot kodi... But not really helping. Sometimes it just accepts finding subs after some time, but sometimes it just refused and I have to find subs on other add-ons...

Hope you'll figure out and can fix it.

Thanks !

**Comment by romanvm** [comment]
Haven't you seen the issue template when creating this issue? If yes, please provide all the necessary info specified in it. Otherwise this issue will be closed as non-informative.
