### ISSUE TITLE
Unable to determine episode data

### ISSUE THREAD

**Issue by quthla** [romanvm/service.addic7ed#21]
**Issue description:**

Filename parsing fails for "The Flash S05E05 mkv"

It's probably better to replace all blanks with dots before parsing the filename. Then the regexes could also be simplified because no more blanks need to be matched.

**Comment by romanvm** [comment]
Such name makes no sense because it has no extension. "The Flash S05E05.mkv" is parsed totally fine.

**Comment by quthla** [comment]
It's just the title, not the actual filename but it is what the addon tries to parse and fails obviously.
I don't see any disadvantages replacing the spaces with dots, do you?

The full title is something like "The Flash S05E05 HDTV [...] mkv" but in either way, without a dot following season / episode, none of the regexes will match.

**Comment by quthla** [comment]
Is there any problem with my proposal?

I also noticed manual search will not work if it can't parse episode data. That also needs fixing

**Comment by romanvm** [comment]
>Is there any problem with my proposal?

Yes, my lack of time. It's an edge case so it's low in my priorities list. Any help with pull requests is always welcome.
