### ISSUE TITLE
Addon crashes with "addic7ed.com error" or "Unable to connect to addic7ed.com" when trying to search for subtitles

### ISSUE THREAD

**Issue by fragmental** [romanvm/service.addic7ed#29]
**Issue description:**
When I load up a video and try to search for subtitles, the addon crashes with an error "addic7ed7.com error" or "Unable to connect to addic7ed.com"

**Kodi debug log:**
Here is a complete log, with debug logging on when I receive the "addic7ed.com error":
https://paste.kodi.tv/lijojapomi.kodi
Here is a copy of the relevant error, with debug logging off:
https://paste.kodi.tv/ajazuyuqaw.kodi
I was going to post a clean copy of the "Unable to connect to addic7ed.com" error but now it just sort of freezes, and sometimes I can't get Kodi to close afterward.
Here's a log from that: 
https://paste.kodi.tv/gusasubewe.kodi
I was finally able to get a log with the connection error, but it's not clean:
https://paste.kodi.tv/ufometexup.kodi

**Comment by romanvm** [comment]
I don't see any connection errors as such. If there were ones, they would indicate problems with Addic7ed.com site itself. There is a problem with getting subtitles for a non-medialibrary item (from an video plugin as it seems) due to recent changes in the addon and I'll fix it as soon as I can.
