### ISSUE TITLE
Unable to connect to addic7ed.com

### ISSUE THREAD

**Issue by lajawi** [romanvm/service.addic7ed#32]
**Issue description:**
When trying to open the service Addic7ed.com in the download subtitles menu, an error appears. It says `Unable to connect to addic7ed.com`
![grafik](https://user-images.githubusercontent.com/51792807/218252539-8b356689-cb14-4d29-89bd-bbfaf9252fd5.png)

**Comment by romanvm** [comment]
Closed as lacking mandatory information as described in the bug report template.
