### ISSUE TITLE
Full subtitle description

### ISSUE THREAD

**Issue by panizza** [romanvm/service.addic7ed#4]
Hi, first I wanted to say thank you, it's nice to see a working Kodi addon available directly in Kodi's repo.

Is it possible to have the full subtitle's description shown in the result list and not just the version? 
Maybe even adding an option in the plugin config section for it.

Thanks

**Comment by romanvm** [comment]
What do you mean by "full subtitle's description"? As far as I can see, Addic7ed does not provide any description for subtitles beyond what is already displayed by the plugin.

**Comment by panizza** [comment]
The old plugin I was using, acted as follow:
Assume you are searching subtitles for the episode "The.Good.Place.S03E12.1080p.HTDV-KILLERS.mkv".
The plugins only display KILLERS, NTB, CRAVERS, TBS etc, instead of "The.Good.Place.S03E12.1080p.HDTV-KILLERS" or "The.Good.Place.S03E12.720p.WEB-DL.TBS". 
I hope it's clearer now.

**Comment by romanvm** [comment]
Again, Addic7ed.com does not provide such information, only release codes, and some subs can be compatible with several releases . I can't add what does not exist on the site.

**Comment by romanvm** [comment]
I'm closing this issue as not relevant.
