### ISSUE TITLE
Result sorting

### ISSUE THREAD

**Issue by Jean85** [romanvm/service.addic7ed#5]
Hi! Thank you very much for this plugin, it's great!

I would like to suggest a small improvement: result sorting.

I use this plugin with two languages enabled, and I would like to see the the `sync` result at the top; does it make sense?

**Comment by romanvm** [comment]
Makes sense. I'll consider this.

**Comment by quthla** [comment]
Can you maybe make it an option to also sort CC subs last? I guess most people don't need CC so it would make it easier if they come last.

**Comment by romanvm** [comment]
@quthla It is not possible without overcomplicated logic which I don't like. Anyway, I'm closing this issue because the original request has been implemented in the latest release.
