### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by rerem8433** [romanvm/service.addic7ed#7]
Hi,

First : thanks for this new add-on, it works very well =)

I have only one question => in description you say that if we login to addic7ed' account into configuration' add-on it will unshow uncompleted subtitles.

It seems it doesn't work for me, I've completed my pseudo and password into configuration and use Exodus to show and launch for "The Flash S05e15". When I search subtitles, your add-on shows me 5 subtitles for french language. On the site it appears there is only 2 subtitles completed for french.

'Ve I wrong on a step ?

Thanks for your work =)

**Comment by romanvm** [comment]
Since I don't use translated subtitles, I'm not familiar with this part of Addic7ed.com site well enough. Please provide links to subtitle pages and screenshots so that I could see how I can make the plugin better recognize and separate incomplete translations.

**Comment by romanvm** [comment]
I'm closing this issue because of no follow-up.
