### ISSUE TITLE
French translation ;)

### ISSUE THREAD

**Issue by rerem8433** [romanvm/service.addic7ed#8]
If you need/want, I've translated a strings.po for french language ti incorporate for your project ;)

Here it is, I hope I've don't forget something or made a mistake.

Have a good day =)

# XBMC Media Center language file
msgid ""
msgstr ""

"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fr\n"

msgctxt "#32000"
msgid "Succès!"
msgstr ""

msgctxt "#32001"
msgid "Sous-titres téléchargés."
msgstr ""

msgctxt "#32002"
msgid "Erreur!"
msgstr ""

msgctxt "#32003"
msgid "Limite journalière de téléchargements dépassée."
msgstr ""

msgctxt "#32004"
msgid "Erreur lors du téléchargement."
msgstr ""

msgctxt "#32005"
msgid "Impossible de se connecter à addic7ed.com."
msgstr ""

msgctxt "#32006"
msgid "Impossible d'identifier les données de l'épisode."
msgstr ""

msgctxt "#32007"
msgid "Toujours utiliser le nom de fichier pour une recherche"
msgstr ""

msgctxt "#32008"
msgid "Sélectionner l'épisode"
msgstr ""

msgctxt "#32009"
msgid "Erreur de connexion!"
msgstr ""

msgctxt "#32010"
msgid "Connexion à Addic7ed.com"
msgstr ""

msgctxt "#32011"
msgid "Nom utilisateur"
msgstr ""

msgctxt "#32012"
msgid "Mot de passe"
msgstr ""

msgctxt "#32013"
msgid "Effacer les cookies"
msgstr ""

msgctxt "#32014"
msgid "Cela va vous déconnecter de Addic7ed.com."
msgstr ""

msgctxt "#32015"
msgid "Êtes-vous sûr(e)?"
msgstr ""

msgctxt "#32016"
msgid "Cookies effacés avec succès."
msgstr ""

msgctxt "#32017"
msgid "Impossible d'effacer les cookies!"
msgstr ""

**Comment by romanvm** [comment]
Thank you for your efforts. However, the translation format is wrong. You should not change `msgid` field. Translations go into `msgstr` fields. And please use triple triple ticks ``` above and below code blocks to format hem like this:
```
this is
a code block
```

**Comment by Memphis017** [comment]
Here it is :

```# XBMC Media Center language file
msgid ""
msgstr ""

"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fr\n"


msgctxt "#32000"
msgid "Success!"
msgstr "Succès!"

msgctxt "#32001"
msgid "Subtitles downloaded."
msgstr "Sous-titres téléchargés."

msgctxt "#32002"
msgid "Error!"
msgstr "Erreur!"

msgctxt "#32003"
msgid "Exceeded daily limit for subs downloads."
msgstr "Limite journalière de téléchargements dépassée."

msgctxt "#32004"
msgid "Unable to download subtitles."
msgstr "Erreur lors du téléchargement."

msgctxt "#32005"
msgid "Unable to connect to addic7ed.com."
msgstr "Impossible de se connecter à addic7ed.com."

msgctxt "#32006"
msgid "Unable to determine episode data."
msgstr "Impossible d'identifier les données de l'épisode."

msgctxt "#32007"
msgid "Always use filename for subs search"
msgstr "Toujours utiliser le nom de fichier pour les recherches"

msgctxt "#32008"
msgid "Select episode"
msgstr "Sélectionner l'épisode"

msgctxt "#32009"
msgid "Login error!"
msgstr "Erreur de connexion!"

msgctxt "#32010"
msgid "Login to Addic7ed.com"
msgstr "Connexion à Addic7ed.com"

msgctxt "#32011"
msgid "Username"
msgstr "Nom utilisateur"

msgctxt "#32012"
msgid "Password"
msgstr "Mot de passe"

msgctxt "#32013"
msgid "Clean cookies"
msgstr "Effacer les cookies"

msgctxt "#32014"
msgid "This will logout you from Addic7ed.com."
msgstr "Cela va vous déconnecter de Addic7ed.com."

msgctxt "#32015"
msgid "Are you sure?"
msgstr "Êtes-vous sûr(e)?"

msgctxt "#32016"
msgid "Cookies removed successfully."
msgstr "Cookies effacés avec succès."

msgctxt "#32017"
msgid "Unable to remove cookies!"
msgstr "Impossible d'effacer les cookies!"
```

**Comment by rerem8433** [comment]
@Memphis017 Merci d'avoir poursuivi et corrigé ma traduction ;)
@romanvm Is it well for integration to your addon ?
Thanks

**Comment by romanvm** [comment]
Thank you. This will go into the next release.

**Comment by romanvm** [comment]
@Memphis017 @rerem8433 To make it complete could you also provide translations for `summary` and `description`: https://github.com/romanvm/service.addic7ed/blob/master/service.subtitles.rvm.addic7ed/addon.xml#L19 ?

**Comment by Memphis017** [comment]
No problem, created a pull request for it :
https://github.com/romanvm/service.addic7ed/pull/16

**Comment by Memphis017** [comment]
Created another pull for strings.po : https://github.com/romanvm/service.addic7ed/pull/18

**Comment by romanvm** [comment]
Added to v.3.1.1.
